name: Frontend Deploy
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"
  release:
    types: [published]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install
      - name: Generate
        working-directory: ./frontend
        run: npm run generate
        env:
          API_URL: https://api.cometlify.com
          IMAGE_SERVING_URL: https://cdn.cometlify.com
          VER: ${{ github.ref }}
          SITE_NAME: "Cometlify"
          SITE_DESCRIPTION: "Cometlify is a website for keeping track of your NFT collections"
          SITE_IMAGE_URL: https://cdn.cometlify.com/permanent/android-chrome-384x384.png
          SITE_CONTACT_EMAIL: hello@cometlify.com
          SITE_DISCORD_LINK: https://discord.gg/CpSWfub9y6
          SITE_GITHUB_REPOSITORY_URL: https://github.com/big213/cometlify
          LOGO_HAS_LIGHT_VARIANT:
          DEFAULT_GRID_VIEW:
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./frontend
